version: "3"
services:

  django:
    image: ndujay/evalai-staging-backend:${COMMIT_ID}
    env_file:
      - docker/prod/docker_staging.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - "8000:8000"

  celery:
    image: ndujay/evalai-staging-celery:${COMMIT_ID}
    env_file:
      - docker/prod/docker_staging.env
    build:
      context: ./
      dockerfile: docker/prod/celery/Dockerfile
    depends_on:
      - django

  worker:
    image: ndujay/evalai-staging-worker:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    env_file:
      - docker/prod/docker_staging.env

  nodejs:
    image: ndujay/evalai-staging-frontend:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/nodejs/Dockerfile
      args:
        NODE_ENV: staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /code/node_modules
      - /code/bower_components

  remote-worker:
    image: ndujay/evalai-staging-remote-worker:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    command: ["python", "-m", "scripts.workers.remote_submission_worker"]
    env_file:
      - docker/prod/docker_remote_worker.env
